-- REPORT 3
-- LEVEL 2

SELECT * FROM(SELECT FLIGHT_YEAR, 
CASE 
  WHEN TO_CHAR(FLIGHT_TYPE) = TO_CHAR(1) THEN 'Domestic' 
  WHEN TO_CHAR(FLIGHT_TYPE) = TO_CHAR(2) THEN 'International'
  ELSE 'Any Types'
END AS FLIGHT_TYPE,
CASE 
  WHEN TO_CHAR(FLIGHT_CLASS) = TO_CHAR(1) THEN 'First Class'
  WHEN TO_CHAR(FLIGHT_CLASS) = TO_CHAR(2) THEN 'Business Class'
  WHEN TO_CHAR(FLIGHT_CLASS) = TO_CHAR(3) THEN 'Economy Class'
  ELSE 'Any Class'
END AS FLIGHT_CLASS, 
SOURCE_COUNTRY, DESTINATION_COUNTRY, NUMBER_OF_TRANSACTIONS,AVERAGE_AGENT_PROFIT 
FROM (SELECT 
EXTRACT(YEAR FROM TO_DATE(T.DATEID, 'DDMMYYYY')) AS FLIGHT_YEAR, 
DECODE(GROUPING(T.FLIGHTTYPEID), 1, 'Any Type', T.FLIGHTTYPEID) AS FLIGHT_TYPE, 
DECODE(GROUPING(T.CLASSID) , 1, 'Any Class', T.CLASSID) AS FLIGHT_CLASS, 
DECODE(GROUPING(S.COUNTRY), 1, 'Any Country', S.COUNTRY) AS SOURCE_COUNTRY, 
DECODE(GROUPING(D.COUNTRY), 1, 'Any Country', D.COUNTRY) AS DESTINATION_COUNTRY,
SUM(T.TOTAL_PASSENGERS) AS NUMBER_OF_TRANSACTIONS, SUM(T.TOTAL_AGENT_PROFIT)/SUM(T.TOTAL_PASSENGERS) AS AVERAGE_AGENT_PROFIT
FROM TRANSACTION_FACT_2 T, SOURCE_AIRPORTS_DIM_2 S, DESTIN_AIRPORTS_DIM_2 D
WHERE T.SOURCEAIRPORTID = S.SOURCEAIRPORTID AND T.DESTAIRPORTID = D.DESTAIRPORTID
GROUP BY EXTRACT( YEAR FROM TO_DATE(T.DATEID, 'DDMMYYYY')), CUBE(T.FLIGHTTYPEID, T.CLASSID, S.COUNTRY, D.COUNTRY) ORDER BY EXTRACT(YEAR FROM TO_DATE(T.DATEID, 'DDMMYYYY')) ASC)) ORDER BY NUMBER_OF_TRANSACTIONS DESC;


-- LEVEL 0

SELECT 
EXTRACT(YEAR FROM TO_DATE(DATEID, 'DD-MM-YY')) AS FLIGHT_YEAR, 
DECODE(GROUPING(FLIGHT_TYPE), 1, 'Any Type', FLIGHT_TYPE) AS FLIGHT_TYPE, 
DECODE(GROUPING(FLIGHT_CLASS) , 1, 'Any Class', FLIGHT_CLASS) AS FLIGHT_CLASS, 
DECODE(GROUPING(SOURCE_COUNTRY), 1, 'Any Country', SOURCE_COUNTRY) AS SOURCE_COUNTRY, 
DECODE(GROUPING(DEST_COUNTRY), 1, 'Any Country', DEST_COUNTRY) AS DESTINATION_COUNTRY,
SUM(TOTAL_TRANSACTIONS) AS NUMBER_OF_TRANSACTIONS, SUM(TOTAL_PROFIT)/SUM(TOTAL_TRANSACTIONS) AS AVERAGE_AGENT_PROFIT
FROM (
SELECT CASE
    WHEN TOTAL_PAID_TICKET >=2*FARE THEN 'First Class'
    WHEN TOTAL_PAID_TICKET >= 1.5*FARE AND TOTAL_PAID_TICKET < 2*FARE  THEN 'Business Class'
    WHEN TOTAL_PAID_TICKET < 1.5*FARE THEN 'First Class'
END AS FLIGHT_CLASS,
DATEID, CASE
    WHEN SOURCE_COUNTRY = DEST_COUNTRY THEN 'Domestic'
    WHEN SOURCE_COUNTRY != DEST_COUNTRY THEN 'International'
    END AS FLIGHT_TYPE, SOURCE_COUNTRY, DEST_COUNTRY, SUM(TOTAL_PASSENGERS) AS TOTAL_TRANSACTIONS, SUM(TOTAL_AGENT_PROFIT) AS TOTAL_PROFIT FROM TRANSACTION_FACT GROUP BY CASE
    WHEN TOTAL_PAID_TICKET >=2*FARE THEN 'First Class'
    WHEN TOTAL_PAID_TICKET >= 1.5*FARE AND TOTAL_PAID_TICKET < 2*FARE  THEN 'Business Class'
    WHEN TOTAL_PAID_TICKET < 1.5*FARE THEN 'First Class' END, 
DATEID, CASE
    WHEN SOURCE_COUNTRY = DEST_COUNTRY THEN 'Domestic'
    WHEN SOURCE_COUNTRY != DEST_COUNTRY THEN 'International'
    END, SOURCE_COUNTRY, DEST_COUNTRY
)
GROUP BY EXTRACT( YEAR FROM TO_DATE(DATEID, 'DD-MM-YY')), CUBE(FLIGHT_TYPE, FLIGHT_CLASS, SOURCE_COUNTRY, DEST_COUNTRY) ORDER BY EXTRACT(YEAR FROM TO_DATE(DATEID, 'DD-MM-YY')) ASC;
