-- REPORT 6
-- LEVEL 2

SELECT D.COUNTRY, D.CITY, SUM(R.TOTAL_INCOMING_ROUTES) AS TOTAL_INCOMING_ROUTES,
DENSE_RANK() OVER(PARTITION BY D.COUNTRY ORDER BY SUM(R.TOTAL_INCOMING_ROUTES) DESC) AS CITY_RANK
FROM ROUTE_FACT_2 R, DESTIN_AIRPORTS_DIM_2 D WHERE R.DESTAIRPORTID = D.DESTAIRPORTID
GROUP BY D.COUNTRY, D.CITY;

-- LEVEL 0

SELECT D.COUNTRY, D.CITY, SUM(R.TOTAL_INCOMING_ROUTES) AS TOTAL_INCOMING_ROUTES,
DENSE_RANK() OVER(PARTITION BY D.COUNTRY ORDER BY SUM(R.TOTAL_INCOMING_ROUTES) DESC) AS CITY_RANK
FROM ROUTE_FACT R, DESTIN_AIRPORTS_DIM D WHERE R.DESTAIRPORTID = D.DESTAIRPORTID
GROUP BY D.COUNTRY, D.CITY;