-- REPORT 7
-- LEVEL 2

SELECT 
DECODE(GROUPING(S.CITY), 1, 'Any City', S.CITY) AS DEPARTURE_CITY,
DECODE(GROUPING(S.COUNTRY), 1, 'Any Country', S.COUNTRY) AS DEPARTURE_COUNTRY, 
DECODE(GROUPING(D.CITY) , 1, 'Any City', D.CITY) AS ARRIVAL_CITY, 
DECODE(GROUPING(S.COUNTRY), 1, 'Any Country', S.COUNTRY) AS ARRIVAL_COUNTRY, 
SUM(R.TOTAL_NUMBER_OF_ROUTES) AS NUMBER_OF_ROUTES,
SUM(R.TOTAL_DISTANCE)/COUNT(R.TOTAL_DISTANCE) AS AVERAGE_DISTANCE
FROM ROUTE_FACT_2 R, SOURCE_AIRPORTS_DIM_2 S, DESTIN_AIRPORTS_DIM_2 D
WHERE R.SOURCEAIRPORTID = S.SOURCEAIRPORTID AND R.DESTAIRPORTID = D.DESTAIRPORTID
GROUP BY CUBE(S.CITY, S.COUNTRY, D.CITY, D.COUNTRY);

-- LEVEL 0

SELECT 
DECODE(GROUPING(S.CITY), 1, 'Any City', S.CITY) AS DEPARTURE_CITY,
DECODE(GROUPING(S.COUNTRY), 1, 'Any Country', S.COUNTRY) AS DEPARTURE_COUNTRY, 
DECODE(GROUPING(D.CITY) , 1, 'Any City', D.CITY) AS ARRIVAL_CITY, 
DECODE(GROUPING(S.COUNTRY), 1, 'Any Country', S.COUNTRY) AS ARRIVAL_COUNTRY, 
SUM(R.TOTAL_NUMBER_OF_ROUTES) AS NUMBER_OF_ROUTES,
SUM(R.TOTAL_DISTANCE)/COUNT(R.TOTAL_DISTANCE) AS AVERAGE_DISTANCE
FROM ROUTE_FACT R, SOURCE_AIRPORTS_DIM S, DESTIN_AIRPORTS_DIM D
WHERE R.SOURCEAIRPORTID = S.SOURCEAIRPORTID AND R.DESTAIRPORTID = D.DESTAIRPORTID
GROUP BY CUBE(S.CITY, S.COUNTRY, D.CITY, D.COUNTRY);