-- ################################################ Exploration ##############################################

-- AIRCRAFTS

SELECT IATACODE, WAKECATEGORY FROM OPFL.AIRCRAFTS WHERE WAKECATEGORY NOT IN ('M', 'L', 'H');
SELECT * FROM OPFL.AIRCRAFTS WHERE MODEL IS NULL;

-- FLIGHTS

SELECT * FROM OPFL.FLIGHTS WHERE FARE < 0;
SELECT * FROM OPFL.FLIGHTS WHERE AIRCRAFTID NOT IN (SELECT IATACODE FROM OPFL.AIRCRAFTS);

-- TRANSACTIONS
SELECT * FROM OPFL.TRANSACTIONS WHERE FLIGHTID NOT IN (SELECT FLIGHTID FROM OPFL.FLIGHTS);

-- PASSENGERS
SELECT * FROM OPFL.PASSENGERS WHERE AGE < 0;

-- ROUTES
SELECT * FROM OPFL.ROUTES WHERE DISTANCE < 0;

-- AIRLINES
SELECT * FROM OPFL.AIRLINES WHERE AIRLINEID < 0;
SELECT * FROM OPFL.AIRLINES WHERE COUNTRY = 'Unknown';

-- AIRPORT
SELECT NAME, LONGITUDE, LATITUDE, CITY, COUNTRY, COUNT(ICAO) FROM OPFL.AIRPORTS GROUP BY NAME, LONGITUDE, LATITUDE, CITY, COUNTRY HAVING COUNT(ICAO) > 1;
SELECT * FROM OPFL.AIRPORTS WHERE NAME = 'Goroka';

-- MENTION
SELECT * FROM OPFL.AIRLINES WHERE IATACODE IS NULL;
SELECT * FROM OPFL.AIRLINES WHERE ICAO IS NULL;
SELECT * FROM OPFL.AIRLINES WHERE CALLSIGN IS NULL;
SELECT * FROM OPFL.AIRPORTS WHERE IATA_FAACODE IS NULL;
SELECT * FROM OPFL.AIRPORTS WHERE ICAO IS NULL;

-- ################################################ Cleaning ##############################################

CREATE TABLE AIRPORTS_2 AS SELECT * FROM OPFL.AIRPORTS;
DELETE FROM AIRPORTS_2 WHERE AIRPORTID < 0;

CREATE TABLE AIRLINES_2 AS SELECT * FROM OPFL.AIRLINES;
DELETE FROM AIRLINES_2 WHERE AIRLINEID < 0;
DELETE FROM AIRLINES_2 WHERE ACTIVE NOT IN ('Y', 'N');

CREATE TABLE ROUTES_2 AS SELECT * FROM OPFL.ROUTES;
DELETE FROM ROUTES_2 WHERE ROUTEID < 0;

CREATE TABLE AIRCRAFTS_2 AS SELECT * FROM OPFL.AIRCRAFTS;
DELETE FROM AIRCRAFTS_2 WHERE WAKECATEGORY NOT IN ('L', 'M', 'H');

CREATE TABLE FLIGHTS_2 AS SELECT * FROM OPFL.FLIGHTS;
DELETE FROM FLIGHTS_2 WHERE FARE < 0;

CREATE TABLE PASSENGERS_2 AS SELECT * FROM OPFL.PASSENGERS;
DELETE FROM PASSENGERS_2 WHERE AGE < 0;

CREATE TABLE TRANSACTIONS_2 AS SELECT * FROM OPFL.TRANSACTIONS;
DELETE FROM TRANSACTIONS_2 WHERE FLIGHTID NOT IN (SELECT FLIGHTID FROM FLIGHTS_2);

CREATE TABLE AIRLINE_SERVICES_2 AS SELECT * FROM OPFL.AIRLINE_SERVICES;

CREATE TABLE PROVIDES_2 AS SELECT * FROM OPFL.PROVIDES;

CREATE TABLE PROMOTION_2 AS SELECT * FROM OPFL.PROMOTION;
-- TO HANDLE NULL VALUES
INSERT INTO PROMOTION_2 VALUES ('P6', 0, TO_DATE('01-01-05', 'DD-MM-YY'), TO_DATE('31-12-14', 'DD-MM-YY'));

CREATE TABLE MEMBERSHIPTYPE_2 AS SELECT * FROM OPFL.MEMBERSHIPTYPE;

CREATE TABLE MEMBERSHIPJOINRECORDS_2 AS SELECT * FROM OPFL.MEMBERSHIPJOINRECORDS;
-- REMOVING NULLS
UPDATE MEMBERSHIPJOINRECORDS_2
SET PROMOTION = 'P6'
WHERE PROMOTION IS NULL;

