-- REPORT 8
-- LEVEL 2


SELECT * FROM(SELECT NATIONALITY,
CASE 
  WHEN TO_CHAR(PASSENGER_TYPE) = TO_CHAR(1) THEN 'Children' 
  WHEN TO_CHAR(PASSENGER_TYPE) = TO_CHAR(2) THEN 'Teenager'
  WHEN TO_CHAR(PASSENGER_TYPE) = TO_CHAR(3) THEN 'Adult'
  WHEN TO_CHAR(PASSENGER_TYPE) = TO_CHAR(4) THEN 'Elder'
  ELSE 'Any'
END AS PASSENGER_TYPE,
SOURCE_COUNTRY, DESTINATION_COUNTRY, AVERAGE_PASSENGER_AGE 
FROM (SELECT 
T.NATIONALITY AS NATIONALITY, 
DECODE(GROUPING(T.CATEGORYID), 1, 'Any ', T.CATEGORYID) AS PASSENGER_TYPE, 
DECODE(GROUPING(S.COUNTRY) , 1, 'Any', S.COUNTRY) AS SOURCE_COUNTRY, 
DECODE(GROUPING(D.COUNTRY), 1, 'Any', D.COUNTRY) AS DESTINATION_COUNTRY,
SUM(T.TOTAL_FLIGHT_AGES)/SUM(T.TOTAL_PASSENGERS) AS AVERAGE_PASSENGER_AGE
FROM TRANSACTION_FACT_2 T, SOURCE_AIRPORTS_DIM_2 S, DESTIN_AIRPORTS_DIM_2 D
WHERE T.SOURCEAIRPORTID = S.SOURCEAIRPORTID AND T.DESTAIRPORTID = D.DESTAIRPORTID
GROUP BY T.NATIONALITY, ROLLUP(T.CATEGORYID, S.COUNTRY, D.COUNTRY) ORDER BY NATIONALITY ASC));


-- LEVEL 0

-- PRE-PROCESSING

CREATE TABLE PRE_PRO AS SELECT NATIONALITY, SOURCEAIRPORTID, DESTAIRPORTID, AGE, TOTAL_PASSENGERS FROM TRANSACTION_FACT;

ALTER TABLE PRE_PRO
ADD PASSENGER_TYPE NUMBER;

UPDATE PRE_PRO
SET PASSENGER_TYPE = 1
WHERE AGE <11;

UPDATE PRE_PRO
SET PASSENGER_TYPE = 2
WHERE AGE BETWEEN 11 AND 17;

UPDATE PRE_PRO
SET PASSENGER_TYPE = 3
WHERE AGE BETWEEN 18 AND 60;

UPDATE PRE_PRO
SET PASSENGER_TYPE = 4
WHERE AGE > 60;

SELECT * FROM(SELECT NATIONALITY,
CASE 
  WHEN TO_CHAR(PASSENGER_TYPE) = TO_CHAR(1) THEN 'Children' 
  WHEN TO_CHAR(PASSENGER_TYPE) = TO_CHAR(2) THEN 'Teenager'
  WHEN TO_CHAR(PASSENGER_TYPE) = TO_CHAR(3) THEN 'Adult'
  WHEN TO_CHAR(PASSENGER_TYPE) = TO_CHAR(4) THEN 'Elder'
  ELSE 'Any'
END AS PASSENGER_TYPE,
SOURCE_COUNTRY, DESTINATION_COUNTRY, AVERAGE_PASSENGER_AGE 
FROM (SELECT 
T.NATIONALITY AS NATIONALITY, 
DECODE(GROUPING(T.PASSENGER_TYPE), 1, 'Any ', T.PASSENGER_TYPE) AS PASSENGER_TYPE, 
DECODE(GROUPING(S.COUNTRY) , 1, 'Any', S.COUNTRY) AS SOURCE_COUNTRY, 
DECODE(GROUPING(D.COUNTRY), 1, 'Any', D.COUNTRY) AS DESTINATION_COUNTRY,
SUM(T.AGE)/SUM(T.TOTAL_PASSENGERS) AS AVERAGE_PASSENGER_AGE
FROM PRE_PRO T, SOURCE_AIRPORTS_DIM S, DESTIN_AIRPORTS_DIM D
WHERE T.SOURCEAIRPORTID = S.SOURCEAIRPORTID AND T.DESTAIRPORTID = D.DESTAIRPORTID
GROUP BY T.NATIONALITY, ROLLUP(T.PASSENGER_TYPE, S.COUNTRY, D.COUNTRY) ORDER BY NATIONALITY ASC));

commit;