-- LEVEL 2

--PRE PROCESSING
CREATE TABLE AIRPORTS_PRE AS SELECT * FROM SOURCE_AIRPORTS_DIM_2;
INSERT INTO AIRPORTS_PRE SELECT * FROM DESTIN_AIRPORTS_DIM_2 WHERE DESTAIRPORTID NOT IN (SELECT SOURCEAIRPORTID FROM SOURCE_AIRPORTS_DIM_2);

-- JUST CHANGING COLUMN NAME FOR BETTER READABILITY
ALTER TABLE AIRPORTS_PRE
RENAME COLUMN SOURCEAIRPORTID TO AIRPORTID;

SELECT 
DECODE(GROUPING(A.AIRPORTID), 1, 'All Airports', A.AIRPORTID) AS AIRPORTID,
DECODE(GROUPING(T.AIRLINEID), 1, 'All Airlines', T.AIRLINEID) AS AIRLINEID,
SUM(TOTAL_AGENT_PROFIT) AS TOTAL_AGENT_PROFIT
FROM TRANSACTION_FACT_2 T, AIRPORTS_PRE A
WHERE A.AIRPORTID = T.SOURCEAIRPORTID OR A.AIRPORTID = T.DESTAIRPORTID
GROUP BY CUBE(A.AIRPORTID, T.AIRLINEID) ORDER BY A.AIRPORTID; 

-- LEVEL 0

SELECT 
DECODE(GROUPING(A.AIRPORTID), 1, 'All Airports', A.AIRPORTID) AS AIRPORTID,
DECODE(GROUPING(T.AIRLINEID), 1, 'All Airlines', T.AIRLINEID) AS AIRLINEID,
SUM(TOTAL_AGENT_PROFIT) AS TOTAL_AGENT_PROFIT
FROM TRANSACTION_FACT T, AIRPORTS_PRE A
WHERE A.AIRPORTID = T.SOURCEAIRPORTID OR A.AIRPORTID = T.DESTAIRPORTID
GROUP BY CUBE(A.AIRPORTID, T.AIRLINEID) ORDER BY A.AIRPORTID;