-- LEVEL 2

SELECT EXTRACT( MONTH FROM TO_DATE(JOINDATE, 'DD/MM/YY'))AS MONTH, 
TO_CHAR(SUM(TOTAL_MEMBERSHIPSALES), '9,999,999,999') AS TOTAL_MEMBERSHIPSALES,
TO_CHAR(SUM(SUM(TOTAL_MEMBERSHIPSALES)) OVER (ORDER BY EXTRACT( MONTH FROM TO_DATE(JOINDATE, 'DD/MM/YY')) ROWS UNBOUNDED PRECEDING), '9,999,999,999') AS CUMULATIVE_SALES,
TO_CHAR (AVG(SUM(TOTAL_MEMBERSHIPSALES)) OVER (ORDER BY EXTRACT( MONTH FROM TO_DATE(JOINDATE, 'DD/MM/YY')) ROWS 1 PRECEDING),'9,999,999,999') AS MOVING_SALES_AVG
FROM MEMBERSHIP_SALES_FACT_2
WHERE MEMBERSHIPTYPEID = 'M3' AND EXTRACT( YEAR FROM TO_DATE(JOINDATE, 'DD/MM/YY')) = EXTRACT( YEAR FROM TO_DATE('2009', 'YYYY'))
GROUP BY EXTRACT( MONTH FROM TO_DATE(JOINDATE, 'DD/MM/YY'));

-- LEVEL 0

SELECT EXTRACT( MONTH FROM TO_DATE(JOINDATE, 'DD/MM/YY'))AS MONTH, 
TO_CHAR(SUM(TOTAL_MEMBERSHIPSALES), '9,999,999,999') AS TOTAL_MEMBERSHIPSALES,
TO_CHAR(SUM(SUM(TOTAL_MEMBERSHIPSALES)) OVER (ORDER BY EXTRACT( MONTH FROM TO_DATE(JOINDATE, 'DD/MM/YY')) ROWS UNBOUNDED PRECEDING), '9,999,999,999') AS CUMULATIVE_SALES,
TO_CHAR (AVG(SUM(TOTAL_MEMBERSHIPSALES)) OVER (ORDER BY EXTRACT( MONTH FROM TO_DATE(JOINDATE, 'DD/MM/YY')) ROWS 2 PRECEDING),'9,999,999,999') AS MOVING_SALES_AVG
FROM MEMBERSHIP_SALES_FACT
WHERE MEMBERSHIPTYPEID = 'M3' AND EXTRACT( YEAR FROM TO_DATE(JOINDATE, 'DD/MM/YY')) = EXTRACT( YEAR FROM TO_DATE('2009', 'YYYY'))
GROUP BY EXTRACT( MONTH FROM TO_DATE(JOINDATE, 'DD/MM/YY'));
